language: python
python:
  - '3.7'
install:
  - pip install sphinx sphinx_rtd_theme
  - pip install -r requirements.txt
  - pip install travis-sphinx

script:
    - travis-sphinx build

after_success:
    - travis-sphinx deploy
