language: python
python:
  - '3.7'
install:
  - pip install -q -r requirements.txt
  - pip install sphinx sphinx_rtd_theme
  - pip install travis-sphinx

script:
  - travis-sphinx build

after_success:
  - travis-sphinx deploy
